spring.application.name=NotificationsServiceEduGov

# ===============================
# BASIC CONFIG
# ===============================
server.port=2078
 
 
# ===============================
# DATABASE CONFIG (if using DB)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/notification_db?createDatabaseIfNotExist=true
 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
 
 
# ===============================
# EUREKA CONFIG
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8001/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
 
eureka.instance.prefer-ip-address=true
 
 
# ===============================
# OPTIONAL (CONFIG SERVER)
# ===============================
# Uncomment if using config server
spring.config.import=optional:configserver:http://localhost:8000
 
 
# ===============================
# LOGGING (optional)
# ===============================
logging.level.com.project.edugov=DEBUG