# Identity - Must match the filename in your GitHub
spring.application.name=ACADEMICPROGRAMSERVICEEDUGOV

# SPECIFIC DATABASE CONNECTION FOR ACADEMIC SERVICE
spring.datasource.url=jdbc:mysql://localhost:3306/edugov_academic_db?createDatabaseIfNotExist=true
# spring.datasource.username=root
# spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Networking & Service Discovery
server.port=8085
eureka.client.service-url.defaultZone=http://localhost:8001/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost

# Config Server Connection
spring.config.import=optional:configserver:http://localhost:8000

# Server configuration
server.tomcat.basedir=.tomcat


spring.cloud.openfeign.circuitbreaker.enabled=false

# Timeout for making a connection to the SMTP server (5 seconds)
spring.mail.properties.mail.smtp.connectiontimeout=5000
# Timeout for waiting for a response from the SMTP server (5 seconds)
spring.mail.properties.mail.smtp.timeout=5000
# Timeout for writing the email data to the server (5 seconds)
spring.mail.properties.mail.smtp.writetimeout=5000

# Allows the security context to be accessible in @Async threads
spring.security.strategy=MODE_INHERITABLETHREADLOCAL
