
spring.application.name=EurekaService
server.port=8001
 
# Prevent the server from registering with itself
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
 
# Simple UI config
eureka.instance.hostname=localhost