# Service Name and Port
spring.application.name=EurekaService
server.port=8001

# Discovery Server Configuration
# These are set to false because this is the server itself; 
# it shouldn't try to register with or fetch from another Eureka instance.
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Service URL and Instance Settings
# Points back to itself to define the zone for other services
eureka.client.service-url.defaultZone=http://localhost:8001/eureka/

# UI and Network Configuration
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true