
 server.port=8002
spring.application.name=ApiGateway
 
 
 # --- Route for Research Projects ---
spring.cloud.gateway.server.webflux.routes[0].id=report-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://REPORTINGANDANALYTICSSERVICEEDUGOV
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/reports/**


eureka.client.service-url.defaultZone=http://localhost:8001/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost

# Disable the auto-locator so it only uses the routes you defined in Java

# Disable auto-discovery so it strictly follows GatewayConfig.java

spring.cloud.gateway.discovery.locator.enabled=false

