server.port=8002
spring.application.name=API-GATEWAY
spring.main.web-application-type=reactive

#eureka.client.service-url.defaultZone=http://localhost:8001/eureka/
#eureka.instance.prefer-ip-address=true

#management.endpoints.web.exposure.include=gateway,health,info
#management.endpoint.gateway.enabled=true

logging.level.org.springframework.cloud.gateway=DEBUG

eureka.client.service-url.defaultZone=http://localhost:8001/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost
 
# Disable the auto-locator so it only uses the routes you defined in Java
 
# Disable auto-discovery so it strictly follows GatewayConfig.java
 
#spring.cloud.gateway.discovery.locator.enabled=false


# Fix: Ensure indices are clean and sequential
#spring.cloud.gateway.routes[0].id=academic-service-route
#spring.cloud.gateway.routes[0].uri=lb://ACADEMIC-SERVICE
#spring.cloud.gateway.routes[0].predicates[0]=Path=/programs/**,/courses/**,/enrollments/**

spring.cloud.gateway.server.webflux.routes[0].id=academic-service-route
spring.cloud.gateway.server.webflux.routes[0].uri=lb://ACADEMIC-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/programs/**,/courses/**,/enrollments/**