server.port=8002
spring.application.name=ApiGateway


# --- Route for Research Projects ---
spring.cloud.gateway.routes[0].id=research-project-route
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/projects/**
spring.cloud.gateway.routes[0].uri=lb://RESEARCH-GRANT-SERVICE

# --- Route for Grants ---
spring.cloud.gateway.routes[1].id=grant-application-route
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/grants/**
spring.cloud.gateway.routes[1].uri=lb://RESEARCH-GRANT-SERVICE


eureka.client.service-url.defaultZone=http://localhost:8001/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost

# Disable the auto-locator so it only uses the routes you defined in Java

# Disable auto-discovery so it strictly follows GatewayConfig.java

spring.cloud.gateway.discovery.locator.enabled=false


# Add this so the Gateway knows where to send /api/documents/ requests
spring.cloud.gateway.routes[2].id=document-service
spring.cloud.gateway.routes[2].uri=lb://DOCUMENT-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/documents/**

