spring.application.name=ResourceAndInfrastructureService

server.port=2004

spring.config.import=optional:configserver:http://localhost:8000

eureka.client.service-url.defaultZone=http://localhost:8001/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost


spring.datasource.url=jdbc:mysql://localhost:3306/edugov_resource_infra?createDatabaseIfNotExist=true
