spring.application.name=ReportingAndAnalyticsServiceEduGov
 



spring.datasource.url=jdbc:mysql://localhost:3306/report_db?createDatabaseIfNotExist=true
#spring.datasource.username=root
#spring.datasource.password=Root


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true




server.port=2026
spring.config.import=optional:configserver:http://localhost:8000

eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.client.service-url.defaultZone=http://localhost:8001/eureka/