spring.application.name=IdentityServiceEduGov
# SPECIFIC DATABASE CONNECTION FOR IDENTITY SERVICE
spring.datasource.url=jdbc:mysql://localhost:3306/edugov_identity_db?createDatabaseIfNotExist=true
#spring.datasource.username=root
#spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=8006
eureka.client.service-url.defaultZone=http://localhost:8001/eureka/
# Tell the microservice where the Config Server is running
spring.config.import=optional:configserver:http://localhost:8000
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost

<<<<<<< HEAD
#eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1

#spring.application.name=IdentityServiceEduGov
# SPECIFIC DATABASE CONNECTION FOR IDENTITY SERVICE
#spring.datasource.url=jdbc:mysql://localhost:3306/edugov_identity_db?createDatabaseIfNotExist=true
#server.port=2004
#spring.config.import=optional:configserver:http://localhost:8000
#spring.datasource.username=root
#spring.datasource.password=12345
#eureka.instance.prefer-ip-address=true
server.tomcat.basedir=.tomcat
#eureka.client.service-url.defaultZone=http://localhost:8001/eureka/
>>>>>>> refs/remotes/origin/Module_1_Sandesh
