# Service Name and Port
spring.application.name=ConfigService
server.port=8000

# Eureka Discovery Configuration
# Registers this config server so clients can discover it via the registry
eureka.client.service-url.defaultZone=http://localhost:8001/eureka/

# Git Repository Configuration
# Points to the repository containing external configuration files
spring.cloud.config.server.git.uri=https://github.com/SandeshDunbale/config-server-repo-edugov.git
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.skip-ssl-validation=true