

spring.application.name=ConfigService
server.port=8000
 
 
# Tell the config server to register with Eureka so other services can find it
eureka.client.service-url.defaultZone=http://localhost:8001/eureka/
 
# Link to your GitHub Repository containing the properties files
spring.cloud.config.server.git.uri=https://github.com/SandeshDunbale/config-server-repo-edugov.git
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.skip-ssl-validation=true
 
# (Optional) If your GitHub repo is private, add your username and personal access token:
# spring.cloud.config.server.git.username=your-github-username
# spring.cloud.config.server.git.password=your-personal-access-token
